---
# Generated by Terraform. Do not edit by hand.
all:
  hosts:
    elastic-${name}:
      ansible_host: ${private_ip}
      ansible_user: ${ssh_user}
      ansible_connection: ssh
  vars:
    deployment_name: ${name}
    aws_region: ${aws_region}
    domain_name: ${domain_name}
    elastic_ssm_prefix: ${ssm_prefix}
    elastic_version: "${elastic_version}"
    elasticsearch_heap_size: "${heap_size}"
    enable_fleet: ${enable_fleet}
    enable_apm: ${enable_apm}
    data_volume_id: ${data_volume_id}
    elasticsearch_fqdn: ${elasticsearch_fqdn}
    kibana_fqdn: ${kibana_fqdn}
    fleet_fqdn: ${fleet_fqdn}
    apm_fqdn: ${apm_fqdn}
